export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const USER_LOADED = 'USER_LOADED'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const LOAD_PROFILE = 'LOAD_PROFILE'

export const INSERT_USER_TO_DB = 'INSERT_USER_TO_DB'
export const FETCH_USERS_FROM_DB = 'FETCH_USERS_FROM_DB'
export const GET_REPOS_ERROR = 'GET_REPOS_ERROR'

export const GITHUB_ORGS_REPOS = 'GITHUB_ORGS_REPOS'
export const INSERT_USER_REPOS = 'INSERT_USER_REPOS'
